### ISSUE TITLE
w2w - files crash WolvenKit 

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#106]
Unknown when this bug occurred, but w2w files now crash the kit at the moment.

**Comment by Traderain** [comment]
No idea why this is happening but gonna investigate.

**Comment by Traderain** [comment]
Should be fixed in 68b0a514812eb3a6d846842fcc7ed02d1497dfbd

**Comment by KoalaNalle** [comment]
Novingrad works at least, but levels\prolog_village_winter\prolog_village.w2w still crashes

**Comment by rfuzzo** [comment]
works too now. what's left is a ton of unknown bytes but no crashing on open.
